name: Build/Deploy app to Azure/GH Environment

env:
  AZURE_WEBAPP_NAME: BrianBlackmanTest     # set this to the name of your Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6'                 # set this to the .NET Core version to use
#  PROJECT_PATH: '/src/brianblackmantest'
on:
#  push:
#    branches:
#      - main
 workflow_dispatch:
  inputs:
    deployapp:
      description: 'Deploy App'
      required: true
      default: 'false'
        
#      webappname:
#        description: 'Web App Name'
#        required: true
#        default: 'MyApp'
        
#        use in workflow: '${{ github.event.inputs.webappname }}'

jobs:
  build1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

#      - name: Set up .NET Core
#        uses: actions/setup-dotnet@v2
#        with:
#          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}

      - name: Build with dotnet
        run: dotnet build \src --configuration Release

      - name: dotnet publish
        run: dotnet publish \src -c Release -o publish

#       - name: Upload artifact for deployment job
#         uses: actions/upload-artifact@v3
#         with:
#           name: .net-app
#           path: publish

  deploy1:
    runs-on: ubuntu-latest
    needs: build1
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          restore-keys: |
            ${{ runner.os }}-nuget-
    
#       - if: github.event.inputs.deployapp == 'true'
#         name: Download artifact from build job
#         uses: actions/download-artifact@v3
#         with:
#           name: .net-app

      - if: github.event.inputs.deployapp == 'true'
        name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_Env }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
