name: dotnetcore/DemoContainer
on:
  workflow_dispatch:
env:
  containerRegistry: "$YOUR_ACR_URL"
  dockerRegistryServiceConnection: "$YOUR_SERVICE_CONNECTION"
  dockerfilePath: "$YOUR_DOCKERFILE_PATH"
  imageRepository: "$YOUR_IMAGE_REPOSITORY"
  tag: "$YOUR_TAG"
  vmImageName: ubuntu-latest
jobs:
  Build:
    env:
      DOCKER_REGISTRY:
      DOCKER_USERNAME:
    name: Build
    runs-on:
      - self-hosted
      - "${{ env.vmImageName }}"
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    # Unable to determine registry '$(dockerRegistryServiceConnection)' type. The service connection was not found or the authentication type not supported.
    - name: Build and push an image to container registry
      uses: docker/login-action@v3.0.0
      with:
        registry: "${{ env.DOCKER_REGISTRY }}"
        username: "${{ env.DOCKER_USERNAME }}"
        password: "${{ secrets.DOCKER_PASSWORD }}"
    # Unable to determine registry '$(dockerRegistryServiceConnection)' type. The service connection was not found or the authentication type not supported.
    - name: Build and push an image to container registry
      run: docker build . --file "${{ env.dockerfilePath }}" -t ${{ env.DOCKER_REGISTRY }}/${{ env.imageRepository }}:${{ env.tag }}
    # Unable to determine registry '$(dockerRegistryServiceConnection)' type. The service connection was not found or the authentication type not supported.
    - name: Build and push an image to container registry
      run: docker push ${{ env.DOCKER_REGISTRY }}/${{ env.imageRepository }}:${{ env.tag }}
